### ISSUE TITLE
PHP 5.6.27 make errors

### ISSUE THREAD

**Issue by designinlife** [vanillahsu/pecl-qrencode#1]
/bin/sh /data/downloads/exts/pecl-qrencode-master/libtool --mode=compile cc  -I. -I/data/downloads/exts/pecl-qrencode-master -DPHP_ATOM_INC -I/data/downloads/exts/pecl-qrencode-master/include -I/data/downloads/exts/pecl-qrencode-master/main -I/data/downloads/exts/pecl-qrencode-master -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /data/downloads/exts/pecl-qrencode-master/qrencode.c -o qrencode.lo 
mkdir .libs
 cc -I. -I/data/downloads/exts/pecl-qrencode-master -DPHP_ATOM_INC -I/data/downloads/exts/pecl-qrencode-master/include -I/data/downloads/exts/pecl-qrencode-master/main -I/data/downloads/exts/pecl-qrencode-master -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /data/downloads/exts/pecl-qrencode-master/qrencode.c  -fPIC -DPIC -o .libs/qrencode.o
In file included from /usr/include/png.h:538,
                 from /data/downloads/exts/pecl-qrencode-master/qrencode.c:28:
/usr/include/pngconf.h:390: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token
/usr/include/pngconf.h:391: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘include’
make: *** [qrencode.lo] Error 1

qrencode-libs-3.4.2-1.el6.x86_64
qrencode-devel-3.4.2-1.el6.x86_64
qrencode-3.4.2-1.el6.x86_64

**Comment by vanillahsu** [comment]
Which linux distribution you use?
