### ISSUE TITLE
Error logs in php 8.0

### ISSUE THREAD

**Issue by cyrilst** [vanillahsu/pecl-qrencode#2]
Hi,

with php 8.0, these errors appear when I start the php-fpm process:
[11-Mar-2022 17:21:31 UTC] PHP Warning:  Missing arginfo for qr_encode() in Unknown on line 0
[11-Mar-2022 17:21:31 UTC] PHP Warning:  Missing arginfo for qr_save() in Unknown on line 0

There was no such error in php 7.4

OS:
FreeBSD 13.0-RELEASE-p7

Packages (installed with pkg, quarterly repository):
php80-8.0.15
php80-pecl-qrencode-0.7

Thanks

**Comment by vanillahsu** [comment]
Hi:

I just released 0.8 to fix arginfo issue, maybe you can try it?

--
but I don't have time to make it compatible with php7.

**Comment by cyrilst** [comment]
Thanks a lot!

I just tested with a fresh jail. I installed `php80` with `pkg`, then `pecl-qrencode` with `portsnap` and `make`.

It works perfectly, and there are no more error in logs.

For php7, pecl-qrencode version 0.7 works nicely, I think there is no need to upgrade it.
